### Dodawanie nowej książki
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Wiedźmin: Ostatnie Życzenie",
  "author": "Andrzej Sapkowski",
  "releaseYear": 1993,
  "isbn": "9788375906254"
}